In [1]:
import pandas as pd
from datetime import datetime
import matplotlib
import json

In [2]:
# Must keep header none to drop breaklines
scored_tweets = pd.read_csv("datasources/scored_tweets.csv", header=None, skiprows= [0])
scored_tweets

,0,1,2,3,4,5
0,2021-10-30,Saturday,0,1454251694813065222,We closed the week strong thanks to #tesla. Wh...,1
1,2021-10-30,Saturday,0,1454251685476376580,30-10-2021 02:00:01 https://t.co/QSSPnxvGl1 #B...,1
2,2021-10-30,Saturday,0,1454251626231906308,"Yeah, so I actually closed out all my position...",0
3,2021-10-30,Saturday,0,1454251613518970880,Well done\nWon a #Tesla \n#wrapped buy #BabyDo...,1
4,2021-10-30,Saturday,0,1454251609760935939,@JilianneParker @Tesla Facts!!,0
...,...,...,...,...,...,...
33510,2021-11-04,Thursday,23,1456406233544544267,@Jon4Lakers @Tesla @elonmusk I love my @Tesla!!!,1
33511,2021-11-04,Thursday,23,1456406218998697989,@BerkmanOnlyfans @JordanUhl Not only that but ...,0
33512,2021-11-04,Thursday,23,1456406216222003203,@TomGardnerFool @AndyCCross @asitmap Mine are ...,1
33513,2021-11-04,Thursday,23,1456406190812975106,@ciphar_TheViper @elonmusk @Tesla @SpaceX @bor...,1
33514,2021-11-04,Thursday,23,1456406172739702786,@MoosaviNafas @elonmusk @RealSkyWatcher @thesh...,1

In [3]:
scored_tweets.dtypes

0    object
1    object
2     int64
3     int64
4    object
5     int64
dtype: object

In [4]:
# Change column names and reorder columns
scored_tweets.columns = ['created_date','weekday','hours','id','tweet', 'score']
scored_tweets

,created_date,weekday,hours,id,tweet,score
0,2021-10-30,Saturday,0,1454251694813065222,We closed the week strong thanks to #tesla. Wh...,1
1,2021-10-30,Saturday,0,1454251685476376580,30-10-2021 02:00:01 https://t.co/QSSPnxvGl1 #B...,1
2,2021-10-30,Saturday,0,1454251626231906308,"Yeah, so I actually closed out all my position...",0
3,2021-10-30,Saturday,0,1454251613518970880,Well done\nWon a #Tesla \n#wrapped buy #BabyDo...,1
4,2021-10-30,Saturday,0,1454251609760935939,@JilianneParker @Tesla Facts!!,0
...,...,...,...,...,...,...
33510,2021-11-04,Thursday,23,1456406233544544267,@Jon4Lakers @Tesla @elonmusk I love my @Tesla!!!,1
33511,2021-11-04,Thursday,23,1456406218998697989,@BerkmanOnlyfans @JordanUhl Not only that but ...,0
33512,2021-11-04,Thursday,23,1456406216222003203,@TomGardnerFool @AndyCCross @asitmap Mine are ...,1
33513,2021-11-04,Thursday,23,1456406190812975106,@ciphar_TheViper @elonmusk @Tesla @SpaceX @bor...,1
33514,2021-11-04,Thursday,23,1456406172739702786,@MoosaviNafas @elonmusk @RealSkyWatcher @thesh...,1

In [6]:
scored_tweets.to_csv("datasources/scored_data.csv", index=True)

In [8]:
scored_tweets.to_json("datasources/scored_data.json", orient="records")

In [6]:
hourly_sample = scored_tweets.groupby(["weekday","hours"]).sample(n=200, random_state=1)

In [12]:
hourly_sample.to_csv("datasources/hourly_sample.csv", index=True)

In [10]:
hourly_sample.to_json("datasources/test_hourly_sample.json", orient="split")

In [11]:
by_weekday = hourly_sample.groupby(["weekday"])

In [15]:
by_weekday.to_json("datasources/test_by_weekday.json", orient="records")

,created_date,weekday,hours,id,tweet,score
11227,2021-11-01,Monday,0,1454975557158899713,@cleantechnica Companies (Tesla) don’t have a ...,0
11209,2021-11-01,Monday,0,1454975914752843784,@VM14872497 @VKVQ17 Thanks for info. Reminds m...,1
11203,2021-11-01,Monday,0,1454976024517779458,@elonmusk @garycruz @truth_tesla @zshahan3 @ga...,0
11271,2021-11-01,Monday,0,1454974995004751872,@SawyerMerritt Good choice! I also got a matte...,1
11353,2021-11-01,Monday,0,1454973867458396160,@Bignate1315 @oygpreston @ShannonSharpe I must...,1
159,2021-10-30,Saturday,0,1454248865813581827,@DirtyTesla @RandyStine @MercedesBenz @Tesla @...,1
136,2021-10-30,Saturday,0,1454249211306786819,@feelikeastrnger @theMJ_effect Just ordered my...,1
162,2021-10-30,Saturday,0,1454248734527606785,@RobinhoodApp @BoredApeYC @Sothebys @Tesla @Ro...,0
133,2021-10-30,Saturday,0,1454249279787356164,@stavrakis_peter @RobinhoodApp @BoredApeYC @So...,1
123,2021-10-30,Saturday,0,1454249476395180032,"No $TSLA sales in the ARK-funds today, these a...",1
5301,2021-10-31,Sunday,0,1454613882325118977,@WholeMarsBlog @elonmusk @hsumacher @Tesla Ple...,1
5400,2021-10-31,Sunday,0,1454612025569681411,@MatchasmMatt @WholeMarsBlog @elonmusk And hav...,0
5447,2021-10-31,Sunday,0,1454611227657789442,@elonmusk @hsumacher @Tesla Thank you Ford and...,1
5402,2021-10-31,Sunday,0,1454611998776438788,@ShannyGasm I remember the electric chair bein...,0
5478,2021-10-31,Sunday,0,1454610870596681729,@RobinhoodApp @BoredApeYC @Sothebys @Tesla Pro...,0
28346,2021-11-04,Thursday,0,1456063331245174788,@TheMoonCarl @Kodi_Coin 🎁NFT Prize Giveaway🎁\n...,1
28401,2021-11-04,Thursday,0,1456062467151474694,@bradsferguson @elonmusk @Tesla @SavedTesla Ha...,1
28568,2021-11-04,Thursday,0,1456058867830427652,"Westport home offers green features, including...",1
28477,2021-11-04,Thursday,0,1456060855800385536,@_tsla_trader @EliteOptions2 I just gave an ex...,0
28403,2021-11-04,Thursday,0,1456062368136396802,@easycat88 |￣￣￣￣￣￣￣￣￣￣￣￣￣|\n @Kodi_Coi...,0
17296,2021-11-02,Tuesday,0,1455335789768835074,"Trending on #LunarCrush:\n\n""Website leak spar...",1
17069,2021-11-02,Tuesday,0,1455338623147155456,@shibafloki_army @elonmusk @Shibaflokitoken @S...,1
17124,2021-11-02,Tuesday,0,1455337974468591616,"Crm, zs, amzn, tesla, netflix, upstart, modern...",0
17226,2021-11-02,Tuesday,0,1455336597516390408,Today I learned that @elonmusk is African Amer...,1
17324,2021-11-02,Tuesday,0,1455335440660111363,@shibsoldier88 Free tesla draw if you own $20 ...,1
22531,2021-11-03,Wednesday,0,1455699821227036672,CleanTechnica: New 4680 Tesla Batteries vs. So...,1
22615,2021-11-03,Wednesday,0,1455698561417547785,@nytimes Elon Musk said he was ready to invest...,1
22653,2021-11-03,Wednesday,0,1455698059434905605,@Louisbotelho17 @johnauthers @bopinion Yes Gei...,0
22558,2021-11-03,Wednesday,0,1455699444561858567,@SerhatMidyat @elonmusk @Tesla but but its a t...,1
22707,2021-11-03,Wednesday,0,1455697151133028355,"Ford, GM and Toyota started too late in EV pus...",1